### ISSUE TITLE
Посох западного ветра

### ISSUE THREAD

**Issue by Motorka3** [wolfkill3/Choice-Battle#16]
В описании готового предмета кд 20сек, у рецепта 15. Также предлагаю увеличить дальность нажатия на 300 единиц.

**Comment by SStarheart** [comment]
**Исправлено описание рецепта на корректное.**
Предмет очень сильный, в баффе не нуждается.

**Comment by wolfkill3** [comment]
Не закрывай так таски, если его не залайкают или задизлайкают будет очень низкий приоритет
