### ISSUE TITLE
Предложение микро реворка Киллер Би

### ISSUE THREAD

**Issue by ChevalierDCalm** [wolfkill3/Choice-Battle#54]
Изменить механику аркана на что-то вроде Е Рёхея, переместить аркан на Q и сделать доступным всегда, клонов можно либо убрать на доп кнопку либо так же на доп кнопке заменить на покров(условно баффающий аркан или может еще что). 
В морфе "Т" даётся Бомба из нынешней Q2.

**Comment by komelko15** [comment]
Если и делать аркан на Q то не очередным таргетом, а направляющем в сторону абилкой по типу W Гина, так же добавить уменьшение кд в 2 раза  от стандартного времени кулдауна спела при непопадании аркана в цель.

**Comment by PinkieNecro** [comment]
Сделано, но иначе
