### ISSUE TITLE
Изменение Готенкса

### ISSUE THREAD

**Issue by FarFacer** [wolfkill3/Choice-Battle#65]
Сделать что бы Т Готенкса не откидывала в рандомый угол, а в какой то просчитанный( от точки каста или к ней) или это фишка?
Сделать на R, когда её выпустили, ограничение на рендж х2 дальность нажатия спела, если больше пролетела, то отмена. Сделать отмену если цель при контанке с диском не работала на неуязвимых, ломает касты с паузами

**Comment by PinkieNecro** [comment]
Сделано лишь первое
